"""create_table_for_storing_parsed_data

Revision ID: 6010756e79fb
Revises: 
Create Date: 2022-09-13 12:59:36.402230

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6010756e79fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'parsed_data',
        sa.Column('ad_link', sa.String(length=250), nullable=False),
        sa.Column('image_url', sa.String(length=250), nullable=True),
        sa.Column('title', sa.String(length=250), nullable=True),
        sa.Column('currency', sa.String(length=15), nullable=True),
        sa.Column('price', sa.String(length=15), nullable=True),
        sa.Column('city', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('bedrooms', sa.String(), nullable=True),
        sa.Column('date', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('ad_link'),
        sa.UniqueConstraint('ad_link'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsed_data')
    # ### end Alembic commands ###
