version: '3.4'


# This config is for development purposes only


volumes:
  database:

services:
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=db_user123
      - POSTGRES_USER=db_user
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgres/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro
  application:
    network_mode: host
    build: .
    links:
      - database
    volumes:
      - ../app:/app:delegated
